server:
  port: 8081
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Toy638/TINGESO-2
          search-paths: "PEP2/Aplicación-microservicio-avanzado-postgresql/config-data"